# fly.toml app configuration file generated for rust-commerce-catalog on 2025-08-15T22:05:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rust-commerce-catalog'
primary_region = 'iad'

[build]

[env]
  LOG_LEVEL = 'info'
  RUST_ENV = 'production'
  RUST_LOG = 'info'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
