# fly.toml app configuration file generated for rust-commerce-catalog on 2025-08-15T22:05:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rust-commerce-catalog'
primary_region = 'iad'

[build]

[env]
  LOG_LEVEL = 'info'
  RUST_ENV = 'production'
  RUST_LOG = 'info'

# No HTTP service needed - catalog service only communicates via NATS

[[vm]]
  size = 'shared-cpu-1x'

# Machine scaling configuration to keep at least 1 machine running
[machine]
  auto_stop_machines = false
  min_machines_running = 1
