[package]
name = "shared-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = { version = "0.14.1", features = ["derive"] }
prost-types = "0.14.1"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
prost-build = "0.14.1"