name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_ENV: ci

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate manifest casing and location
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
          # Ensure the canonical manifest exists at the repo root
          if [ ! -f Cargo.toml ]; then
            echo "ERROR: Cargo.toml not found at repository root ($GITHUB_WORKSPACE)." >&2
            exit 1
          fi
          # Fail fast if any lowercase cargo.toml sneaks in (case-sensitive on Linux runners)
          LOWER=$(find . -type f -iname 'cargo.toml' ! -name 'Cargo.toml' || true)
          if [ -n "$LOWER" ]; then
            echo "ERROR: Found non-canonical manifest filenames (expected 'Cargo.toml'):" >&2
            echo "$LOWER" >&2
            echo "Hint: rename with 'git mv -f cargo.toml Cargo.toml' and commit the change." >&2
            exit 1
          fi
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate manifest casing and location
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
          if [ ! -f Cargo.toml ]; then
            echo "ERROR: Cargo.toml not found at repository root ($GITHUB_WORKSPACE)." >&2
            exit 1
          fi
          LOWER=$(find . -type f -iname 'cargo.toml' ! -name 'Cargo.toml' || true)
          if [ -n "$LOWER" ]; then
            echo "ERROR: Found non-canonical manifest filenames (expected 'Cargo.toml'):" >&2
            echo "$LOWER" >&2
            exit 1
          fi
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler pkg-config libssl-dev
      - name: Linting
        run: cargo clippy --workspace --all-targets -- -D warnings

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate manifest casing and location
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
          if [ ! -f Cargo.toml ]; then
            echo "ERROR: Cargo.toml not found at repository root ($GITHUB_WORKSPACE)." >&2
            exit 1
          fi
          LOWER=$(find . -type f -iname 'cargo.toml' ! -name 'Cargo.toml' || true)
          if [ -n "$LOWER" ]; then
            echo "ERROR: Found non-canonical manifest filenames (expected 'Cargo.toml'):" >&2
            echo "$LOWER" >&2
            exit 1
          fi
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler pkg-config libssl-dev
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build workspace
        run: cargo build --workspace --all-targets
      - name: Run unit tests (libs & bins)
        run: |
          cargo test --workspace --lib --bins

  integration-tests:
    name: Integration tests (MongoDB + NATS)
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:7
        ports: [ '27017:27017' ]
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password123
      nats:
        image: nats:latest
        ports: [ '4222:4222', '8222:8222' ]
    env:
      MONGODB_URL: mongodb://admin:password123@localhost:27017/?authSource=admin
      NATS_URL: nats://127.0.0.1:4222
      NATS_TEST_URL: nats://127.0.0.1:4222
      RUST_LOG: info
    steps:
      - uses: actions/checkout@v4
      - name: Validate manifest casing and location
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la
          if [ ! -f Cargo.toml ]; then
            echo "ERROR: Cargo.toml not found at repository root ($GITHUB_WORKSPACE)." >&2
            exit 1
          fi
          LOWER=$(find . -type f -iname 'cargo.toml' ! -name 'Cargo.toml' || true)
          if [ -n "$LOWER" ]; then
            echo "ERROR: Found non-canonical manifest filenames (expected 'Cargo.toml'):" >&2
            echo "$LOWER" >&2
            exit 1
          fi
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler pkg-config libssl-dev netcat-openbsd
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Wait for MongoDB
        run: |
          for i in {1..30}; do
            if nc -z 127.0.0.1 27017; then echo "MongoDB is up"; exit 0; fi
            echo "Waiting for MongoDB..."; sleep 2;
          done
          echo "MongoDB did not start in time"; exit 1
      - name: Wait for NATS
        run: |
          for i in {1..30}; do
            if nc -z 127.0.0.1 4222; then echo "NATS is up"; exit 0; fi
            echo "Waiting for NATS..."; sleep 2;
          done
          echo "NATS did not start in time"; exit 1
      - name: Build workspace
        run: cargo build --workspace --all-targets
      - name: Start catalog-service
        run: |
          RUST_LOG=debug nohup cargo run -p rust-catalog --bin catalog-service >/tmp/catalog.log 2>&1 &
          echo $! > /tmp/catalog.pid
      - name: Start inventory-service
        run: |
          RUST_LOG=debug nohup cargo run -p rust-inventory --bin inventory-service >/tmp/inventory.log 2>&1 &
          echo $! > /tmp/inventory.pid
      - name: Start order-service
        run: |
          RUST_LOG=debug nohup cargo run -p rust-orders --bin order-service >/tmp/orders.log 2>&1 &
          echo $! > /tmp/orders.pid
      - name: Start price-service
        run: |
          RUST_LOG=debug nohup cargo run -p rust-price --bin price-service >/tmp/price.log 2>&1 &
          echo $! > /tmp/price.pid
      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start and register with NATS..."
          sleep 15
          
          # Check if services are still running
          for service in catalog inventory orders price; do
            if [ -f /tmp/${service}.pid ]; then
              pid=$(cat /tmp/${service}.pid)
              if ! kill -0 $pid 2>/dev/null; then
                echo "ERROR: ${service}-service process is not running"
                echo "=== ${service} service log ==="
                cat /tmp/${service}.log
                echo "=========================="
                exit 1
              else
                echo "${service}-service is running (PID: $pid)"
              fi
            fi
          done
          
          echo "All services appear to be running. Service logs:"
          for service in catalog inventory orders price; do
            echo "=== ${service} service startup log ==="
            head -20 /tmp/${service}.log
            echo "=========================="
          done
      - name: Test service NATS connectivity
        run: |
          echo "Testing NATS connectivity to services..."
          # Test basic NATS connection
          cargo run -p rust-inventory --bin inventory-client -- --help >/dev/null 2>&1 || echo "Inventory client build check passed"
          
          # Check NATS server status
          curl -s http://127.0.0.1:8222/connz | head -20 || echo "Could not get NATS connection info"
          
          # Wait a bit more for NATS subscriptions to be fully established
          sleep 5
          
          echo "Services should now be ready for integration tests"
      - name: Run integration tests
        run: cargo test --workspace --tests -- --nocapture
      - name: Upload service logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: service-logs-failure
          path: |
            /tmp/catalog.log
            /tmp/inventory.log
            /tmp/orders.log
            /tmp/price.log
      - name: Upload service logs for debugging
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: service-logs-debug
          path: |
            /tmp/catalog.log
            /tmp/inventory.log
            /tmp/orders.log
            /tmp/price.log

  deploy:
    name: Deploy to Fly.io
    needs: [fmt, clippy, unit-tests, integration-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Catalog service
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd scripts
          flyctl deploy .. -c catalog/fly.toml --remote-only --yes
      - name: Deploy Inventory service
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd scripts
          flyctl deploy .. -c inventory/fly.toml --remote-only --yes
      - name: Deploy Orders service
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd scripts
          flyctl deploy .. -c orders/fly.toml --remote-only --yes
      - name: Deploy Price service
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          cd scripts
          flyctl deploy .. -c price/fly.toml --remote-only --yes
